GPII-2810: Onboard Windows 10 "Personalization" -> "Colors"
GPII/windows pull request #196
Opened 2018-09-05 11:10 UTC by JavierJF

2018-09-10 14:54 UTC, stegru requested changes
Similar stylistic things to https://github.com/GPII/windows/pull/197.

If there's a reason not to call the system settings handler via the solutions registry, then we can sort that out rather than call it via code.

2018-09-10 14:54 UTC, stegru commented on gpii/node_modules/accentColorsSettingsHandler/src/colorManager.csx
> +    public static bool isGet(Object[] input) {
Upper case the first letter.

Built-in type keywords (such as `object`, `int`, and `string`) are preferred, instead of the .NET type names `Object`, `Int32`, `String`

2018-09-10 14:54 UTC, stegru commented on gpii/node_modules/accentColorsSettingsHandler/src/colorManager.csx
> +            bool isString = input[0].GetType() == typeof(System.String);
can use the `is` operator instead.. `input[0] is string`

Or just `input[0] as string == "get"`

2018-09-10 14:54 UTC, stegru commented on gpii/node_modules/accentColorsSettingsHandler/src/colorManager.csx
> +            bool isSet = ((String)input[0]) == "set";
This will crash if `input[0]` is not something that can't be casted to a string. See above comment for an alternative, or perform the cast after checking `isString`.

2018-09-10 14:54 UTC, stegru commented on gpii/node_modules/accentColorsSettingsHandler/src/colorManager.csx
> +        ImmersiveColorPreference colorPreference = new ImmersiveColorPreference { crStartColor = 0, crAccentColor = 0 };
Redundant assignment (see next line)

2018-09-10 14:54 UTC, stegru commented on gpii/node_modules/accentColorsSettingsHandler/src/colorManager.csx
> +        DwmColorParams colorParams = new DwmColorParams {
The assignment is not needed, it will be overwritten on the next line with `out` (same again for next method)

2018-09-10 14:54 UTC, stegru commented on gpii/node_modules/accentColorsSettingsHandler/src/colorManager.csx
> +            ColorizationAfterglow = 0x00007fff,
These aren't needed anyway, `colorParams` is re-assigned on the next line by the `out` keyword.

2018-09-10 14:54 UTC, stegru commented on gpii/node_modules/accentColorsSettingsHandler/src/accentColorSettingsHandler.js
> +    request.settings.SystemSettings_Personalize_Color_EnableAutoColor = {
The system settings handler should be called via the solutions registry, rather directly via code.

2018-09-10 14:54 UTC, stegru commented on gpii/node_modules/accentColorsSettingsHandler/src/accentColorSettingsHandler.js
> + * @param {object} payload The payload.
`{Object}`

2018-09-10 14:54 UTC, stegru commented on gpii/node_modules/accentColorsSettingsHandler/src/accentColorSettingsHandler.js
> +    payload = payload.settings;
Redefinition of a parameter. Either use the full name or introduce another variable, `settings`.

2018-09-10 14:54 UTC, stegru commented on gpii/node_modules/accentColorsSettingsHandler/src/accentColorSettingsHandler.js
> +                if (result !== 0) {
Just `result` will do (or change to `===` and swap the blocks).

For an `if`/`else`, it's usually more readable to perform positive checks.

2018-09-10 14:54 UTC, stegru commented on gpii/node_modules/accentColorsSettingsHandler/src/colorManager.csx
> +            return -10;
Undocumented (or incorrect) return value.

2018-09-27 17:36 UTC, JavierJF commented on gpii/node_modules/accentColorsSettingsHandler/src/accentColorSettingsHandler.js
> +        return fluid.get(payload, "color.value") !== undefined;
I think it's okay for the cases with no nested fields, but in the case of nested ones, I think it's not, because I use it to determined if the payload have that option. I case of 'setting' being undefined for that payload, it means that the setting is not requested.

2018-10-02 20:43 UTC, JavierJF commented on gpii/node_modules/accentColorsSettingsHandler/src/accentColorSettingsHandler.js
> +    request.settings.SystemSettings_Personalize_Color_EnableAutoColor = {
Yes, but the calling order is important, also I needed to code several settings into one. Which is the color option, that were the reasons to encode settings handled by the systemSettingsHandler into another handler.

2018-10-02 20:44 UTC, JavierJF commented on gpii/node_modules/accentColorsSettingsHandler/src/colorManager.csx
> +            bool isString = input[0].GetType() == typeof(System.String);
Okay, will go for that for cleaner syntax.

2018-10-02 22:36 UTC, amb26 commented on gpii/node_modules/accentColorsSettingsHandler/src/accentColorSettingsHandler.js
> +    var input = (payload.color.value === "auto") ? true : false;
This ternary is unnecessary

2018-10-02 22:39 UTC, amb26 commented on gpii/node_modules/accentColorsSettingsHandler/src/accentColorSettingsHandler.js
> +windows.accentColor.getImpl = function (payload) {
Why do we here access this as windows.accentColor but above as simply accentColor? In general our standard is not to assign to intermediates but refer to fully qualified names such as gpii.windows.accentColor - this helps with searching for reads/writes using our (nonexistent) tools

2018-10-02 22:40 UTC, amb26 commented on gpii/node_modules/accentColorsSettingsHandler/src/accentColorSettingsHandler.js
> +var windows = fluid.registerNamespace("gpii.windows");
These two variables are unnecessary

2018-10-02 22:42 UTC, amb26 commented on gpii/node_modules/accentColorsSettingsHandler/src/accentColorSettingsHandler.js
> +    Object.keys(sysResults).forEach(function (elem) {
fluid.each is a touch more direct and efficient

2018-10-02 22:42 UTC, amb26 commented on gpii/node_modules/accentColorsSettingsHandler/src/accentColorSettingsHandler.js
> +    var idMaps = {
Stick this into a public constant

2018-10-02 22:43 UTC, amb26 commented on gpii/node_modules/accentColorsSettingsHandler/src/accentColorSettingsHandler.js
> + * @return {Object} A valid request for the systemSettingsHandler.
Be more specific here with an @typedef where this is returned here and also where it appears as a parameter

2019-02-06 14:02 UTC, stegru commented on gpii/node_modules/accentColorsSettingsHandler/src/colorManager.csx
> +    [DllImport("dwmapi.dll", EntryPoint = "#131", CallingConvention = CallingConvention.StdCall)]
https://www.geoffchappell.com/studies/windows/win32/dwmapi/api/index.htm

2020-10-13 14:57 UTC, closed without merging